$env:env="HTTP"
$env:cloud_env="aws"
$env:storage_bucket="kidsloop-global-resources-test"
$env:storage_region="ap-northeast-2"
$env:secret_id= "AKIAXGKUAYT2P2IJ2KX7"
$env:secret_key= "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"

$env:storage_accelerate="true"
$env:cdn_open="false"
$env:max_repeat_year="10"
$env:open_cache="true"
$env:redis_host="172.22.20.171"
$env:redis_port="6379"
$env:redis_password=""
$env:db_env="mysql"
$env:connection_string="root:Badanamu123456@tcp(172.22.20.171:3306)/kidsloop2?parseTime=true&charset=utf8mb4"
$env:max_open_conns="8"
$env:max_idle_conns="4"
$env:show_log="true"
$env:show_sql="true"

go run main.go