name: Setting Go Cache
description: Setting the Go Cache


inputs:
  GIT_TOKEN:
    required: true
    description: "Git Token"


runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Configure git credentials
      shell: bash
      run: |
        git config --global url.https://${{ inputs.GIT_TOKEN }}@github.com/.insteadOf https://github.com/