CREATE TABLE `learning_outcomes` (
   `id` VARCHAR(50) NOT  NULL  COMMENT  'outcome_id',
   `ancestor_id` VARCHAR(50)  NOT  NULL  COMMENT  'ancestor_id',
   `shortcode` CHAR(50)  NOT  NULL  COMMENT  'ancestor_id',
   `name` VARCHAR( 255) NOT  NULL  COMMENT  'outcome_name',
   `program` VARCHAR( 1024) NOT  NULL  COMMENT  'program',
   `subject` VARCHAR( 1024) NOT  NULL  COMMENT  'subject',
   `developmental` VARCHAR( 1024) NOT  NULL  COMMENT  'developmental',
   `skills` VARCHAR( 1024) NOT  NULL  COMMENT  'skills',
   `age` VARCHAR( 1024) NOT  NULL  COMMENT  'age',
   `grade` VARCHAR( 1024) NOT  NULL  COMMENT  'grade',
   `keywords` TEXT  NULL  COMMENT  'keywords',
   `description` TEXT  NULL  COMMENT  'description',
   `estimated_time` int  NOT  NULL  COMMENT  'estimated_time',
   `author_id` VARCHAR( 50) NOT  NULL  COMMENT  'author_id',
   `author_name` VARCHAR( 128) NOT  NULL  COMMENT  'author_name',
   `organization_id` VARCHAR( 50) NOT  NULL  COMMENT  'organization_id',
   `publish_scope` VARCHAR( 50) COMMENT  'publish_scope, default as the organization_id',
   `publish_status` VARCHAR( 16) NOT  NULL  COMMENT  'publish_status',
   `reject_reason` VARCHAR( 255) COMMENT  'reject_reason',
   `version` INT  NOT  NULL  DEFAULT  0  COMMENT  'version',
   `assumed` TINYINT  NOT  NULL  DEFAULT  0  COMMENT  'assumed',
   `locked_by` VARCHAR( 50) COMMENT  'locked by who',
   `source_id` VARCHAR( 50) COMMENT  'source_id',
   `latest_id` VARCHAR( 50) COMMENT  'latest_id',
   `create_at` BIGINT  NOT  NULL  COMMENT  'created_at',
   `update_at` BIGINT  NOT  NULL  COMMENT  'updated_at',
   `delete_at` BIGINT  NULL  COMMENT  'deleted_at',
   PRIMARY KEY (`id`),
    KEY `index_ancestor_id` (`ancestor_id`),
    KEY `index_latest_id` (`latest_id`),
    KEY `index_publish_status` (`publish_status`),
    KEY `index_source_id` (`source_id`),
    FULLTEXT INDEX `fullindex_name_description_keywords_author_shortcode` (`name`, `keywords`, `description`, `author_name`, `shortcode`) WITH PARSER ngram
) COMMENT 'outcomes table';
