name: Deploy to Swagger

on:
  push:
    branches:
      - swag-byron
      - main
  workflow_dispatch:

env:
  BUCKET_KEYS: kidsloop-alpha-cms-intent-turtle
  AWS_REGION: ap-northeast-2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-


    - name: Build SWAG
      run: |
        go env -w GOPROXY="https://goproxy.cn,direct"
        go env -w GOPRIVATE="bitbucket.org"
    - name: Install SWAG
      run: go install github.com/swaggo/swag/cmd/swag@v1.8.1
    - name: Build SWAG
      run: swag init
    # - name: COPY JSON File
    #   run: |
    #     cp docs/swagger.json .
    #     ls -la docs/

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: swag
        path: docs
        if-no-files-found: error
        retention-days: 3

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ALPHA_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ALPHA_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download result
        uses: actions/download-artifact@v3
        with:
          name: swag
      - name: Display structure of downloaded files
        run: |
          ls -la
          echo $PWD
          touch aa.txt
      - name: upload to s3
        run: aws s3 sync aa.txt s3://$BUCKET_KEYS/alpha/latest/swagger