name: Build and Push image to ECR

on:
  push:
    branches:
      - hotfix/*
      - main
      - id-build
  workflow_dispatch:

env:
  H5P_PRIVATE_KEY: ${{ secrets.H5P_PRIVATE_KEY }}
  H5P_PUBLIC_KEY: ${{ secrets.H5P_PUBLIC_KEY }}
  JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
  AMS_ASSESSMENT_JWT_PUBLIC_KEY: ${{ secrets.AMS_ASSESSMENT_JWT_PUBLIC_KEY }}
  LIVE_TOKEN_PRIVATE_KEY: ${{ secrets.LIVE_TOKEN_PRIVATE_KEY }}
  STM_INTERNAL_PUBLIC_KEY: ${{ secrets.STM_INTERNAL_PUBLIC_KEY }}

  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_PORT: ${{secrets.SERVER_PORT}}
  SERVER_DESTINATION: ${{secrets.SERVER_DESTINATION}}

jobs:
  build-to-ecr:
    name: Build And Deploy ECS
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Container
        # uses: KL-Engineering/kidsloop-action-center/.github/actions/gocache@v1.0.0
        uses: ./.github/actions/gocache
        with:
          GIT_TOKEN: ${{ secrets.PACKAGES_TOKEN_SETH }}

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o deploy/handler -ldflags "-X github.com/KL-Engineering/kidsloop-cms-service/constant.GitHash=$(git rev-list -1 HEAD) -X github.com/KL-Engineering/kidsloop-cms-service/constant.BuildTimestamp=$(date +%s) -X github.com/KL-Engineering/kidsloop-cms-service/constant.LatestMigrate=$(ls schema/migrate | tail -1)"

      - name: prepare tokens
        env:
          H5P_PRIVATE_KEY: ${{ env.H5P_PRIVATE_KEY }}
          H5P_PUBLIC_KEY: ${{ env.H5P_PUBLIC_KEY }}
          JWT_PUBLIC_KEY: ${{ env.JWT_PUBLIC_KEY }}
          AMS_ASSESSMENT_JWT_PUBLIC_KEY: ${{ env.AMS_ASSESSMENT_JWT_PUBLIC_KEY }}
          LIVE_TOKEN_PRIVATE_KEY: ${{ env.LIVE_TOKEN_PRIVATE_KEY }}
          STM_INTERNAL_PUBLIC_KEY: ${{ env.STM_INTERNAL_PUBLIC_KEY }}
        run: |
          echo "$H5P_PRIVATE_KEY" | base64 -d > deploy/h5p_private_key.pem
          echo "$H5P_PUBLIC_KEY" | base64 -d > deploy/h5p_public_key.pem
          echo "$JWT_PUBLIC_KEY" | base64 -d > deploy/jwt_public_key.pem
          echo "$AMS_ASSESSMENT_JWT_PUBLIC_KEY" | base64 -d > deploy/ams_assessment_jwt_public_key.pem
          echo "$LIVE_TOKEN_PRIVATE_KEY" | base64 -d > deploy/live_token_private_key.pem
          echo "$STM_INTERNAL_PUBLIC_KEY" | base64 -d > deploy/stm_internal_public_key.pem

      - name: Build and Push Container
        # uses: KL-Engineering/kidsloop-action-center/.github/actions/docker-build-and-push@v1.0.0
        uses: ./.github/actions/docker-build-and-push
        with:
          environment: ${{ needs.generate-version.outputs.tag }}
          region: global
          ecr_repository: kidsloop-cms-backend
          dockerfile_dir: deploy
          dockerfile_name: Dockerfile
          dockerfile_context: .
          ecr_aws_region: ap-southeast-3
          ecr_registry: 789939988543.dkr.ecr.ap-southeast-3.amazonaws.com
          ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ID_ECR_AWS_ACCESS_KEY_ID }}
          ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ID_ECR_AWS_SECRET_ACCESS_KEY }}
